name: Continuous Integration

on:
  push:
    branches:
      - master

jobs:
  build_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master branch
        uses: actions/checkout@v2
      
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      
      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build